import { create } from "zustand";
import getForcastData from "../lib/getForcastData";
import React from "react";

const initialState = {
  data: {
    location: {
      name: "New Delhi",
      region: "Delhi",
      country: "India",
      lat: 28.6,
      lon: 77.2,
      tz_id: "Asia/Kolkata",
      localtime_epoch: 1700258662,
      localtime: "2023-11-18 3:34",
    },
    current: {
      last_updated_epoch: 1700258400,
      last_updated: "2023-11-18 03:30",
      temp_c: 17.0,
      temp_f: 62.6,
      is_day: 0,
      condition: {
        text: "Fog",
        icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
        code: 1135,
      },
      wind_mph: 3.8,
      wind_kph: 6.1,
      wind_degree: 210,
      wind_dir: "SSW",
      pressure_mb: 1016.0,
      pressure_in: 30.0,
      precip_mm: 0.0,
      precip_in: 0.0,
      humidity: 88,
      cloud: 25,
      feelslike_c: 17.0,
      feelslike_f: 62.6,
      vis_km: 0.8,
      vis_miles: 0.0,
      uv: 1.0,
      gust_mph: 5.0,
      gust_kph: 8.0,
    },
    forecast: {
      forecastday: [
        {
          date: "2023-11-19",
          date_epoch: 1700352000,
          day: {
            maxtemp_c: 28.0,
            maxtemp_f: 82.5,
            mintemp_c: 21.0,
            mintemp_f: 69.8,
            avgtemp_c: 24.4,
            avgtemp_f: 76.0,
            maxwind_mph: 4.9,
            maxwind_kph: 7.9,
            totalprecip_mm: 0.0,
            totalprecip_in: 0.0,
            totalsnow_cm: 0.0,
            avgvis_km: 10.0,
            avgvis_miles: 6.0,
            avghumidity: 32.0,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6.0,
          },
          astro: {
            sunrise: "06:46 AM",
            sunset: "05:26 PM",
            moonrise: "12:22 PM",
            moonset: "11:07 PM",
            moon_phase: "Waxing Crescent",
            moon_illumination: 34,
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1700332200,
              time: "2023-11-19 00:00",
              temp_c: 22.5,
              temp_f: 72.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 193,
              wind_dir: "SSW",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 24.2,
              feelslike_f: 75.5,
              windchill_c: 22.5,
              windchill_f: 72.6,
              heatindex_c: 24.2,
              heatindex_f: 75.5,
              dewpoint_c: 8.3,
              dewpoint_f: 46.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.7,
              gust_kph: 5.9,
              uv: 1.0,
            },
            {
              time_epoch: 1700335800,
              time: "2023-11-19 01:00",
              temp_c: 22.2,
              temp_f: 71.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.8,
              wind_kph: 2.9,
              wind_degree: 194,
              wind_dir: "SSW",
              pressure_mb: 1015.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 24.1,
              feelslike_f: 75.3,
              windchill_c: 22.2,
              windchill_f: 71.9,
              heatindex_c: 24.1,
              heatindex_f: 75.3,
              dewpoint_c: 8.1,
              dewpoint_f: 46.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.0,
              gust_kph: 4.8,
              uv: 1.0,
            },
            {
              time_epoch: 1700339400,
              time: "2023-11-19 02:00",
              temp_c: 21.8,
              temp_f: 71.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.3,
              wind_kph: 2.2,
              wind_degree: 201,
              wind_dir: "SSW",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 41,
              cloud: 0,
              feelslike_c: 21.8,
              feelslike_f: 71.2,
              windchill_c: 21.8,
              windchill_f: 71.2,
              heatindex_c: 24.0,
              heatindex_f: 75.2,
              dewpoint_c: 7.9,
              dewpoint_f: 46.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.2,
              gust_kph: 3.6,
              uv: 1.0,
            },
            {
              time_epoch: 1700343000,
              time: "2023-11-19 03:00",
              temp_c: 21.5,
              temp_f: 70.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.3,
              wind_kph: 2.2,
              wind_degree: 188,
              wind_dir: "S",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 41,
              cloud: 0,
              feelslike_c: 21.5,
              feelslike_f: 70.6,
              windchill_c: 21.5,
              windchill_f: 70.6,
              heatindex_c: 24.0,
              heatindex_f: 75.1,
              dewpoint_c: 7.8,
              dewpoint_f: 46.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.2,
              gust_kph: 3.6,
              uv: 1.0,
            },
            {
              time_epoch: 1700346600,
              time: "2023-11-19 04:00",
              temp_c: 17.0,
              temp_f: 62.6,
              is_day: 0,
              condition: {
                text: "Mist",
                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                code: 1030,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 10,
              wind_dir: "N",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 25,
              feelslike_c: 21.1,
              feelslike_f: 70.1,
              windchill_c: 21.1,
              windchill_f: 70.1,
              heatindex_c: 24.0,
              heatindex_f: 75.1,
              dewpoint_c: 7.7,
              dewpoint_f: 45.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2.1,
              vis_miles: 1.0,
              gust_mph: 2.2,
              gust_kph: 3.6,
              uv: 1.0,
            },
            {
              time_epoch: 1700350200,
              time: "2023-11-19 05:00",
              temp_c: 20.9,
              temp_f: 69.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.3,
              wind_kph: 2.2,
              wind_degree: 162,
              wind_dir: "SSE",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 42,
              cloud: 0,
              feelslike_c: 20.9,
              feelslike_f: 69.5,
              windchill_c: 20.9,
              windchill_f: 69.5,
              heatindex_c: 20.9,
              heatindex_f: 69.5,
              dewpoint_c: 7.6,
              dewpoint_f: 45.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.2,
              gust_kph: 3.6,
              uv: 1.0,
            },
            {
              time_epoch: 1700353800,
              time: "2023-11-19 06:00",
              temp_c: 20.6,
              temp_f: 69.0,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.6,
              wind_kph: 2.5,
              wind_degree: 137,
              wind_dir: "SE",
              pressure_mb: 1017.0,
              pressure_in: 30.03,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 43,
              cloud: 0,
              feelslike_c: 20.6,
              feelslike_f: 69.0,
              windchill_c: 20.6,
              windchill_f: 69.0,
              heatindex_c: 20.6,
              heatindex_f: 69.0,
              dewpoint_c: 7.6,
              dewpoint_f: 45.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.6,
              gust_kph: 4.2,
              uv: 1.0,
            },
            {
              time_epoch: 1700357400,
              time: "2023-11-19 07:00",
              temp_c: 20.8,
              temp_f: 69.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.5,
              wind_kph: 4.0,
              wind_degree: 121,
              wind_dir: "ESE",
              pressure_mb: 1018.0,
              pressure_in: 30.05,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 43,
              cloud: 0,
              feelslike_c: 20.8,
              feelslike_f: 69.4,
              windchill_c: 20.8,
              windchill_f: 69.4,
              heatindex_c: 20.8,
              heatindex_f: 69.4,
              dewpoint_c: 7.7,
              dewpoint_f: 45.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.8,
              gust_kph: 6.1,
              uv: 6.0,
            },
            {
              time_epoch: 1700361000,
              time: "2023-11-19 08:00",
              temp_c: 21.8,
              temp_f: 71.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 118,
              wind_dir: "ESE",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 40,
              cloud: 0,
              feelslike_c: 21.8,
              feelslike_f: 71.3,
              windchill_c: 21.8,
              windchill_f: 71.3,
              heatindex_c: 24.0,
              heatindex_f: 75.2,
              dewpoint_c: 7.7,
              dewpoint_f: 45.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.4,
              gust_kph: 7.1,
              uv: 6.0,
            },
            {
              time_epoch: 1700364600,
              time: "2023-11-19 09:00",
              temp_c: 23.2,
              temp_f: 73.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 118,
              wind_dir: "ESE",
              pressure_mb: 1019.0,
              pressure_in: 30.1,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 38,
              cloud: 0,
              feelslike_c: 24.3,
              feelslike_f: 75.7,
              windchill_c: 23.2,
              windchill_f: 73.7,
              heatindex_c: 24.3,
              heatindex_f: 75.7,
              dewpoint_c: 8.0,
              dewpoint_f: 46.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.3,
              gust_kph: 8.5,
              uv: 6.0,
            },
            {
              time_epoch: 1700368200,
              time: "2023-11-19 10:00",
              temp_c: 24.4,
              temp_f: 75.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 120,
              wind_dir: "ESE",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 36,
              cloud: 0,
              feelslike_c: 24.8,
              feelslike_f: 76.6,
              windchill_c: 24.4,
              windchill_f: 75.9,
              heatindex_c: 24.8,
              heatindex_f: 76.6,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.2,
              gust_kph: 9.9,
              uv: 6.0,
            },
            {
              time_epoch: 1700371800,
              time: "2023-11-19 11:00",
              temp_c: 25.4,
              temp_f: 77.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.6,
              wind_kph: 9.0,
              wind_degree: 122,
              wind_dir: "ESE",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 34,
              cloud: 0,
              feelslike_c: 25.3,
              feelslike_f: 77.5,
              windchill_c: 25.4,
              windchill_f: 77.8,
              heatindex_c: 25.3,
              heatindex_f: 77.5,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.4,
              gust_kph: 10.4,
              uv: 7.0,
            },
            {
              time_epoch: 1700375400,
              time: "2023-11-19 12:00",
              temp_c: 26.3,
              temp_f: 79.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 127,
              wind_dir: "SE",
              pressure_mb: 1017.0,
              pressure_in: 30.03,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 30,
              cloud: 0,
              feelslike_c: 25.6,
              feelslike_f: 78.2,
              windchill_c: 26.4,
              windchill_f: 79.4,
              heatindex_c: 25.6,
              heatindex_f: 78.2,
              dewpoint_c: 7.6,
              dewpoint_f: 45.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.9,
              gust_kph: 9.5,
              uv: 7.0,
            },
            {
              time_epoch: 1700379000,
              time: "2023-11-19 13:00",
              temp_c: 27.0,
              temp_f: 80.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 139,
              wind_dir: "SE",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 28,
              cloud: 0,
              feelslike_c: 26.0,
              feelslike_f: 78.7,
              windchill_c: 27.0,
              windchill_f: 80.7,
              heatindex_c: 26.0,
              heatindex_f: 78.7,
              dewpoint_c: 6.9,
              dewpoint_f: 44.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.1,
              gust_kph: 8.3,
              uv: 7.0,
            },
            {
              time_epoch: 1700382600,
              time: "2023-11-19 14:00",
              temp_c: 27.4,
              temp_f: 81.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 151,
              wind_dir: "SSE",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 26,
              cloud: 0,
              feelslike_c: 26.1,
              feelslike_f: 79.0,
              windchill_c: 27.4,
              windchill_f: 81.3,
              heatindex_c: 26.1,
              heatindex_f: 79.0,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.4,
              gust_kph: 7.1,
              uv: 7.0,
            },
            {
              time_epoch: 1700386200,
              time: "2023-11-19 15:00",
              temp_c: 27.5,
              temp_f: 81.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 159,
              wind_dir: "SSE",
              pressure_mb: 1015.0,
              pressure_in: 29.97,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 25,
              cloud: 0,
              feelslike_c: 26.1,
              feelslike_f: 79.0,
              windchill_c: 27.5,
              windchill_f: 81.5,
              heatindex_c: 26.1,
              heatindex_f: 79.0,
              dewpoint_c: 6.0,
              dewpoint_f: 42.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.4,
              gust_kph: 5.4,
              uv: 7.0,
            },
            {
              time_epoch: 1700389800,
              time: "2023-11-19 16:00",
              temp_c: 27.1,
              temp_f: 80.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 164,
              wind_dir: "SSE",
              pressure_mb: 1015.0,
              pressure_in: 29.97,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 26,
              cloud: 0,
              feelslike_c: 25.9,
              feelslike_f: 78.6,
              windchill_c: 27.1,
              windchill_f: 80.8,
              heatindex_c: 25.9,
              heatindex_f: 78.6,
              dewpoint_c: 6.0,
              dewpoint_f: 42.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.8,
              gust_kph: 4.6,
              uv: 7.0,
            },
            {
              time_epoch: 1700393400,
              time: "2023-11-19 17:00",
              temp_c: 26.1,
              temp_f: 79.0,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.6,
              wind_kph: 2.5,
              wind_degree: 173,
              wind_dir: "S",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 27,
              cloud: 0,
              feelslike_c: 25.2,
              feelslike_f: 77.4,
              windchill_c: 26.1,
              windchill_f: 79.0,
              heatindex_c: 25.2,
              heatindex_f: 77.4,
              dewpoint_c: 5.8,
              dewpoint_f: 42.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.4,
              gust_kph: 3.8,
              uv: 1.0,
            },
            {
              time_epoch: 1700397000,
              time: "2023-11-19 18:00",
              temp_c: 25.6,
              temp_f: 78.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.1,
              wind_kph: 1.8,
              wind_degree: 167,
              wind_dir: "SSE",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 28,
              cloud: 0,
              feelslike_c: 24.9,
              feelslike_f: 76.9,
              windchill_c: 25.6,
              windchill_f: 78.1,
              heatindex_c: 24.9,
              heatindex_f: 76.9,
              dewpoint_c: 5.8,
              dewpoint_f: 42.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 1.8,
              gust_kph: 2.9,
              uv: 1.0,
            },
            {
              time_epoch: 1700400600,
              time: "2023-11-19 19:00",
              temp_c: 25.1,
              temp_f: 77.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.3,
              wind_kph: 2.2,
              wind_degree: 144,
              wind_dir: "SE",
              pressure_mb: 1016.0,
              pressure_in: 30.01,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 29,
              cloud: 0,
              feelslike_c: 24.7,
              feelslike_f: 76.4,
              windchill_c: 25.1,
              windchill_f: 77.2,
              heatindex_c: 24.7,
              heatindex_f: 76.4,
              dewpoint_c: 5.9,
              dewpoint_f: 42.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.2,
              gust_kph: 3.6,
              uv: 1.0,
            },
            {
              time_epoch: 1700404200,
              time: "2023-11-19 20:00",
              temp_c: 24.5,
              temp_f: 76.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.6,
              wind_kph: 2.5,
              wind_degree: 132,
              wind_dir: "SE",
              pressure_mb: 1017.0,
              pressure_in: 30.02,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 30,
              cloud: 0,
              feelslike_c: 24.5,
              feelslike_f: 76.0,
              windchill_c: 24.5,
              windchill_f: 76.2,
              heatindex_c: 24.5,
              heatindex_f: 76.0,
              dewpoint_c: 6.0,
              dewpoint_f: 42.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.7,
              gust_kph: 4.3,
              uv: 1.0,
            },
            {
              time_epoch: 1700407800,
              time: "2023-11-19 21:00",
              temp_c: 24.0,
              temp_f: 75.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.8,
              wind_kph: 2.9,
              wind_degree: 124,
              wind_dir: "SE",
              pressure_mb: 1016.0,
              pressure_in: 30.02,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 32,
              cloud: 0,
              feelslike_c: 24.2,
              feelslike_f: 75.6,
              windchill_c: 24.0,
              windchill_f: 75.2,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 6.1,
              dewpoint_f: 43.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.1,
              gust_kph: 5.0,
              uv: 1.0,
            },
            {
              time_epoch: 1700411400,
              time: "2023-11-19 22:00",
              temp_c: 23.5,
              temp_f: 74.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.6,
              wind_kph: 2.5,
              wind_degree: 125,
              wind_dir: "SE",
              pressure_mb: 1016.0,
              pressure_in: 30.01,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 33,
              cloud: 0,
              feelslike_c: 24.1,
              feelslike_f: 75.4,
              windchill_c: 23.5,
              windchill_f: 74.3,
              heatindex_c: 24.1,
              heatindex_f: 75.4,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.8,
              gust_kph: 4.4,
              uv: 1.0,
            },
            {
              time_epoch: 1700415000,
              time: "2023-11-19 23:00",
              temp_c: 23.1,
              temp_f: 73.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.6,
              wind_kph: 2.5,
              wind_degree: 131,
              wind_dir: "SE",
              pressure_mb: 1016.0,
              pressure_in: 30.01,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 34,
              cloud: 0,
              feelslike_c: 24.0,
              feelslike_f: 75.2,
              windchill_c: 23.1,
              windchill_f: 73.5,
              heatindex_c: 24.0,
              heatindex_f: 75.2,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.8,
              gust_kph: 4.5,
              uv: 1.0,
            },
          ],
        },
        {
          date: "2023-11-20",
          date_epoch: 1700438400,
          day: {
            maxtemp_c: 28.6,
            maxtemp_f: 83.5,
            mintemp_c: 21.0,
            mintemp_f: 69.8,
            avgtemp_c: 24.7,
            avgtemp_f: 76.5,
            maxwind_mph: 4.3,
            maxwind_kph: 6.8,
            totalprecip_mm: 0.0,
            totalprecip_in: 0.0,
            totalsnow_cm: 0.0,
            avgvis_km: 10.0,
            avgvis_miles: 6.0,
            avghumidity: 28.0,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6.0,
          },
          astro: {
            sunrise: "06:47 AM",
            sunset: "05:26 PM",
            moonrise: "01:03 PM",
            moonset: "No moonset",
            moon_phase: "First Quarter",
            moon_illumination: 45,
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1700418600,
              time: "2023-11-20 00:00",
              temp_c: 22.7,
              temp_f: 72.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.1,
              wind_kph: 1.8,
              wind_degree: 145,
              wind_dir: "SE",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 35,
              cloud: 0,
              feelslike_c: 23.9,
              feelslike_f: 75.0,
              windchill_c: 22.7,
              windchill_f: 72.8,
              heatindex_c: 23.9,
              heatindex_f: 75.0,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.0,
              gust_kph: 3.2,
              uv: 1.0,
            },
            {
              time_epoch: 1700422200,
              time: "2023-11-20 01:00",
              temp_c: 22.3,
              temp_f: 72.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 0.7,
              wind_kph: 1.1,
              wind_degree: 171,
              wind_dir: "S",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 35,
              cloud: 0,
              feelslike_c: 23.8,
              feelslike_f: 74.9,
              windchill_c: 22.3,
              windchill_f: 72.2,
              heatindex_c: 23.8,
              heatindex_f: 74.9,
              dewpoint_c: 6.4,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 1.2,
              gust_kph: 1.9,
              uv: 1.0,
            },
            {
              time_epoch: 1700425800,
              time: "2023-11-20 02:00",
              temp_c: 21.9,
              temp_f: 71.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 0.4,
              wind_kph: 0.7,
              wind_degree: 239,
              wind_dir: "WSW",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 36,
              cloud: 0,
              feelslike_c: 22.0,
              feelslike_f: 71.5,
              windchill_c: 22.0,
              windchill_f: 71.5,
              heatindex_c: 23.8,
              heatindex_f: 74.8,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 0.8,
              gust_kph: 1.3,
              uv: 1.0,
            },
            {
              time_epoch: 1700429400,
              time: "2023-11-20 03:00",
              temp_c: 21.6,
              temp_f: 70.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 0.7,
              wind_kph: 1.1,
              wind_degree: 305,
              wind_dir: "NW",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 21.6,
              feelslike_f: 70.8,
              windchill_c: 21.6,
              windchill_f: 70.8,
              heatindex_c: 23.7,
              heatindex_f: 74.7,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 1.2,
              gust_kph: 1.9,
              uv: 1.0,
            },
            {
              time_epoch: 1700433000,
              time: "2023-11-20 04:00",
              temp_c: 21.2,
              temp_f: 70.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.3,
              wind_kph: 2.2,
              wind_degree: 327,
              wind_dir: "NNW",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 38,
              cloud: 0,
              feelslike_c: 21.2,
              feelslike_f: 70.1,
              windchill_c: 21.2,
              windchill_f: 70.1,
              heatindex_c: 23.7,
              heatindex_f: 74.7,
              dewpoint_c: 6.3,
              dewpoint_f: 43.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.3,
              gust_kph: 3.8,
              uv: 1.0,
            },
            {
              time_epoch: 1700436600,
              time: "2023-11-20 05:00",
              temp_c: 20.9,
              temp_f: 69.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.0,
              wind_kph: 3.2,
              wind_degree: 338,
              wind_dir: "NNW",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 39,
              cloud: 0,
              feelslike_c: 20.9,
              feelslike_f: 69.6,
              windchill_c: 20.9,
              windchill_f: 69.6,
              heatindex_c: 20.9,
              heatindex_f: 69.6,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.5,
              gust_kph: 5.7,
              uv: 1.0,
            },
            {
              time_epoch: 1700440200,
              time: "2023-11-20 06:00",
              temp_c: 20.6,
              temp_f: 69.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.0,
              wind_kph: 3.2,
              wind_degree: 350,
              wind_dir: "N",
              pressure_mb: 1016.0,
              pressure_in: 30.01,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 39,
              cloud: 0,
              feelslike_c: 20.6,
              feelslike_f: 69.1,
              windchill_c: 20.6,
              windchill_f: 69.1,
              heatindex_c: 20.6,
              heatindex_f: 69.1,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.5,
              gust_kph: 5.7,
              uv: 1.0,
            },
            {
              time_epoch: 1700443800,
              time: "2023-11-20 07:00",
              temp_c: 20.9,
              temp_f: 69.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.0,
              wind_kph: 3.2,
              wind_degree: 0,
              wind_dir: "N",
              pressure_mb: 1017.0,
              pressure_in: 30.03,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 39,
              cloud: 0,
              feelslike_c: 20.9,
              feelslike_f: 69.7,
              windchill_c: 20.9,
              windchill_f: 69.7,
              heatindex_c: 20.9,
              heatindex_f: 69.7,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.3,
              gust_kph: 5.3,
              uv: 6.0,
            },
            {
              time_epoch: 1700447400,
              time: "2023-11-20 08:00",
              temp_c: 22.1,
              temp_f: 71.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 1.8,
              wind_kph: 2.9,
              wind_degree: 23,
              wind_dir: "NNE",
              pressure_mb: 1018.0,
              pressure_in: 30.05,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 23.9,
              feelslike_f: 74.9,
              windchill_c: 22.1,
              windchill_f: 71.8,
              heatindex_c: 23.9,
              heatindex_f: 74.9,
              dewpoint_c: 6.7,
              dewpoint_f: 44.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.4,
              gust_kph: 3.9,
              uv: 6.0,
            },
            {
              time_epoch: 1700451000,
              time: "2023-11-20 09:00",
              temp_c: 23.7,
              temp_f: 74.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 1.6,
              wind_kph: 2.5,
              wind_degree: 19,
              wind_dir: "NNE",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 33,
              cloud: 0,
              feelslike_c: 24.2,
              feelslike_f: 75.6,
              windchill_c: 23.7,
              windchill_f: 74.6,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 6.6,
              dewpoint_f: 44.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 1.8,
              gust_kph: 3.0,
              uv: 6.0,
            },
            {
              time_epoch: 1700454600,
              time: "2023-11-20 10:00",
              temp_c: 25.1,
              temp_f: 77.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 1.3,
              wind_kph: 2.2,
              wind_degree: 350,
              wind_dir: "N",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 30,
              cloud: 0,
              feelslike_c: 24.8,
              feelslike_f: 76.7,
              windchill_c: 25.1,
              windchill_f: 77.3,
              heatindex_c: 24.8,
              heatindex_f: 76.7,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 1.5,
              gust_kph: 2.5,
              uv: 7.0,
            },
            {
              time_epoch: 1700458200,
              time: "2023-11-20 11:00",
              temp_c: 26.4,
              temp_f: 79.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.0,
              wind_kph: 3.2,
              wind_degree: 324,
              wind_dir: "NW",
              pressure_mb: 1017.0,
              pressure_in: 30.04,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 28,
              cloud: 0,
              feelslike_c: 25.5,
              feelslike_f: 77.9,
              windchill_c: 26.4,
              windchill_f: 79.5,
              heatindex_c: 25.5,
              heatindex_f: 77.9,
              dewpoint_c: 6.4,
              dewpoint_f: 43.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.3,
              gust_kph: 3.7,
              uv: 7.0,
            },
            {
              time_epoch: 1700461800,
              time: "2023-11-20 12:00",
              temp_c: 27.2,
              temp_f: 81.0,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 307,
              wind_dir: "NW",
              pressure_mb: 1016.0,
              pressure_in: 30.01,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 26,
              cloud: 0,
              feelslike_c: 25.9,
              feelslike_f: 78.6,
              windchill_c: 27.2,
              windchill_f: 81.0,
              heatindex_c: 25.9,
              heatindex_f: 78.6,
              dewpoint_c: 5.9,
              dewpoint_f: 42.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.6,
              gust_kph: 5.8,
              uv: 7.0,
            },
            {
              time_epoch: 1700465400,
              time: "2023-11-20 13:00",
              temp_c: 27.8,
              temp_f: 82.0,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 306,
              wind_dir: "NW",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 23,
              cloud: 0,
              feelslike_c: 26.2,
              feelslike_f: 79.1,
              windchill_c: 27.8,
              windchill_f: 82.0,
              heatindex_c: 26.2,
              heatindex_f: 79.1,
              dewpoint_c: 5.0,
              dewpoint_f: 41.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 7.0,
            },
            {
              time_epoch: 1700469000,
              time: "2023-11-20 14:00",
              temp_c: 28.2,
              temp_f: 82.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 310,
              wind_dir: "NW",
              pressure_mb: 1014.0,
              pressure_in: 29.95,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 22,
              cloud: 0,
              feelslike_c: 26.4,
              feelslike_f: 79.4,
              windchill_c: 28.2,
              windchill_f: 82.8,
              heatindex_c: 26.4,
              heatindex_f: 79.4,
              dewpoint_c: 4.3,
              dewpoint_f: 39.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 7.0,
            },
            {
              time_epoch: 1700472600,
              time: "2023-11-20 15:00",
              temp_c: 28.3,
              temp_f: 83.0,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1014.0,
              pressure_in: 29.94,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 21,
              cloud: 0,
              feelslike_c: 26.4,
              feelslike_f: 79.4,
              windchill_c: 28.3,
              windchill_f: 83.0,
              heatindex_c: 26.4,
              heatindex_f: 79.4,
              dewpoint_c: 3.8,
              dewpoint_f: 38.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 7.0,
            },
            {
              time_epoch: 1700476200,
              time: "2023-11-20 16:00",
              temp_c: 28.0,
              temp_f: 82.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 303,
              wind_dir: "WNW",
              pressure_mb: 1014.0,
              pressure_in: 29.94,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 21,
              cloud: 1,
              feelslike_c: 26.1,
              feelslike_f: 79.1,
              windchill_c: 28.0,
              windchill_f: 82.5,
              heatindex_c: 26.1,
              heatindex_f: 79.1,
              dewpoint_c: 3.6,
              dewpoint_f: 38.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.9,
              gust_kph: 8.0,
              uv: 7.0,
            },
            {
              time_epoch: 1700479800,
              time: "2023-11-20 17:00",
              temp_c: 27.1,
              temp_f: 80.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 302,
              wind_dir: "WNW",
              pressure_mb: 1014.0,
              pressure_in: 29.95,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 22,
              cloud: 2,
              feelslike_c: 25.4,
              feelslike_f: 77.8,
              windchill_c: 27.1,
              windchill_f: 80.7,
              heatindex_c: 25.4,
              heatindex_f: 77.8,
              dewpoint_c: 3.4,
              dewpoint_f: 38.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.2,
              gust_kph: 8.4,
              uv: 1.0,
            },
            {
              time_epoch: 1700483400,
              time: "2023-11-20 18:00",
              temp_c: 26.3,
              temp_f: 79.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 301,
              wind_dir: "WNW",
              pressure_mb: 1015.0,
              pressure_in: 29.96,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 23,
              cloud: 2,
              feelslike_c: 25.0,
              feelslike_f: 76.9,
              windchill_c: 26.3,
              windchill_f: 79.4,
              heatindex_c: 25.0,
              heatindex_f: 76.9,
              dewpoint_c: 3.3,
              dewpoint_f: 37.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.6,
              gust_kph: 9.1,
              uv: 1.0,
            },
            {
              time_epoch: 1700487000,
              time: "2023-11-20 19:00",
              temp_c: 25.7,
              temp_f: 78.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 304,
              wind_dir: "NW",
              pressure_mb: 1015.0,
              pressure_in: 29.98,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 24,
              cloud: 0,
              feelslike_c: 24.6,
              feelslike_f: 76.3,
              windchill_c: 25.7,
              windchill_f: 78.3,
              heatindex_c: 24.6,
              heatindex_f: 76.3,
              dewpoint_c: 3.4,
              dewpoint_f: 38.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.9,
              gust_kph: 9.4,
              uv: 1.0,
            },
            {
              time_epoch: 1700490600,
              time: "2023-11-20 20:00",
              temp_c: 25.1,
              temp_f: 77.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 322,
              wind_dir: "NW",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 24,
              cloud: 0,
              feelslike_c: 24.3,
              feelslike_f: 75.7,
              windchill_c: 25.1,
              windchill_f: 77.2,
              heatindex_c: 24.3,
              heatindex_f: 75.7,
              dewpoint_c: 3.3,
              dewpoint_f: 38.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.2,
              gust_kph: 8.4,
              uv: 1.0,
            },
            {
              time_epoch: 1700494200,
              time: "2023-11-20 21:00",
              temp_c: 24.6,
              temp_f: 76.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 25,
              cloud: 0,
              feelslike_c: 24.0,
              feelslike_f: 75.2,
              windchill_c: 24.6,
              windchill_f: 76.2,
              heatindex_c: 24.0,
              heatindex_f: 75.2,
              dewpoint_c: 3.3,
              dewpoint_f: 37.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.7,
              gust_kph: 9.1,
              uv: 1.0,
            },
            {
              time_epoch: 1700497800,
              time: "2023-11-20 22:00",
              temp_c: 24.0,
              temp_f: 75.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 319,
              wind_dir: "NW",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 26,
              cloud: 0,
              feelslike_c: 23.8,
              feelslike_f: 74.8,
              windchill_c: 24.0,
              windchill_f: 75.2,
              heatindex_c: 23.8,
              heatindex_f: 74.8,
              dewpoint_c: 3.3,
              dewpoint_f: 37.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.4,
              gust_kph: 10.4,
              uv: 1.0,
            },
            {
              time_epoch: 1700501400,
              time: "2023-11-20 23:00",
              temp_c: 23.5,
              temp_f: 74.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 318,
              wind_dir: "NW",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 27,
              cloud: 0,
              feelslike_c: 23.6,
              feelslike_f: 74.4,
              windchill_c: 23.5,
              windchill_f: 74.3,
              heatindex_c: 23.6,
              heatindex_f: 74.4,
              dewpoint_c: 3.2,
              dewpoint_f: 37.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.6,
              uv: 1.0,
            },
          ],
        },
        {
          date: "2023-11-21",
          date_epoch: 1700524800,
          day: {
            maxtemp_c: 28.9,
            maxtemp_f: 84.0,
            mintemp_c: 20.8,
            mintemp_f: 69.4,
            avgtemp_c: 24.6,
            avgtemp_f: 76.2,
            maxwind_mph: 8.7,
            maxwind_kph: 14.0,
            totalprecip_mm: 0.0,
            totalprecip_in: 0.0,
            totalsnow_cm: 0.0,
            avgvis_km: 10.0,
            avgvis_miles: 6.0,
            avghumidity: 22.0,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6.0,
          },
          astro: {
            sunrise: "06:48 AM",
            sunset: "05:26 PM",
            moonrise: "01:39 PM",
            moonset: "12:14 AM",
            moon_phase: "Waxing Gibbous",
            moon_illumination: 56,
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1700505000,
              time: "2023-11-21 00:00",
              temp_c: 23.0,
              temp_f: 73.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 330,
              wind_dir: "NNW",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 27,
              cloud: 0,
              feelslike_c: 23.4,
              feelslike_f: 74.1,
              windchill_c: 23.1,
              windchill_f: 73.5,
              heatindex_c: 23.4,
              heatindex_f: 74.1,
              dewpoint_c: 3.1,
              dewpoint_f: 37.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 1.0,
            },
            {
              time_epoch: 1700508600,
              time: "2023-11-21 01:00",
              temp_c: 22.6,
              temp_f: 72.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 340,
              wind_dir: "NNW",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 28,
              cloud: 0,
              feelslike_c: 23.3,
              feelslike_f: 73.9,
              windchill_c: 22.6,
              windchill_f: 72.6,
              heatindex_c: 23.3,
              heatindex_f: 73.9,
              dewpoint_c: 3.1,
              dewpoint_f: 37.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 1.0,
            },
            {
              time_epoch: 1700512200,
              time: "2023-11-21 02:00",
              temp_c: 22.0,
              temp_f: 71.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 348,
              wind_dir: "NNW",
              pressure_mb: 1015.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 29,
              cloud: 0,
              feelslike_c: 23.2,
              feelslike_f: 73.7,
              windchill_c: 22.0,
              windchill_f: 71.6,
              heatindex_c: 23.2,
              heatindex_f: 73.7,
              dewpoint_c: 3.1,
              dewpoint_f: 37.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.5,
              gust_kph: 12.0,
              uv: 1.0,
            },
            {
              time_epoch: 1700515800,
              time: "2023-11-21 03:00",
              temp_c: 21.5,
              temp_f: 70.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 338,
              wind_dir: "NNW",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 30,
              cloud: 0,
              feelslike_c: 21.5,
              feelslike_f: 70.8,
              windchill_c: 21.5,
              windchill_f: 70.8,
              heatindex_c: 23.1,
              heatindex_f: 73.6,
              dewpoint_c: 3.2,
              dewpoint_f: 37.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.6,
              gust_kph: 10.6,
              uv: 1.0,
            },
            {
              time_epoch: 1700519400,
              time: "2023-11-21 04:00",
              temp_c: 21.1,
              temp_f: 70.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1015.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 31,
              cloud: 0,
              feelslike_c: 21.1,
              feelslike_f: 70.1,
              windchill_c: 21.1,
              windchill_f: 70.1,
              heatindex_c: 23.1,
              heatindex_f: 73.6,
              dewpoint_c: 3.3,
              dewpoint_f: 38.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.4,
              gust_kph: 8.7,
              uv: 1.0,
            },
            {
              time_epoch: 1700523000,
              time: "2023-11-21 05:00",
              temp_c: 20.9,
              temp_f: 69.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 313,
              wind_dir: "NW",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 31,
              cloud: 0,
              feelslike_c: 20.9,
              feelslike_f: 69.6,
              windchill_c: 20.9,
              windchill_f: 69.6,
              heatindex_c: 20.9,
              heatindex_f: 69.6,
              dewpoint_c: 3.3,
              dewpoint_f: 37.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.7,
              gust_kph: 9.3,
              uv: 1.0,
            },
            {
              time_epoch: 1700526600,
              time: "2023-11-21 06:00",
              temp_c: 20.6,
              temp_f: 69.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 313,
              wind_dir: "NW",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 32,
              cloud: 0,
              feelslike_c: 20.6,
              feelslike_f: 69.1,
              windchill_c: 20.6,
              windchill_f: 69.1,
              heatindex_c: 20.6,
              heatindex_f: 69.1,
              dewpoint_c: 3.3,
              dewpoint_f: 38.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.4,
              gust_kph: 8.7,
              uv: 1.0,
            },
            {
              time_epoch: 1700530200,
              time: "2023-11-21 07:00",
              temp_c: 20.8,
              temp_f: 69.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 316,
              wind_dir: "NW",
              pressure_mb: 1016.0,
              pressure_in: 30.02,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 32,
              cloud: 0,
              feelslike_c: 20.8,
              feelslike_f: 69.5,
              windchill_c: 20.8,
              windchill_f: 69.5,
              heatindex_c: 20.8,
              heatindex_f: 69.5,
              dewpoint_c: 3.5,
              dewpoint_f: 38.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.1,
              gust_kph: 8.3,
              uv: 6.0,
            },
            {
              time_epoch: 1700533800,
              time: "2023-11-21 08:00",
              temp_c: 22.1,
              temp_f: 71.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1017.0,
              pressure_in: 30.03,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 29,
              cloud: 0,
              feelslike_c: 23.2,
              feelslike_f: 73.8,
              windchill_c: 22.1,
              windchill_f: 71.7,
              heatindex_c: 23.2,
              heatindex_f: 73.8,
              dewpoint_c: 3.4,
              dewpoint_f: 38.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.2,
              gust_kph: 8.4,
              uv: 6.0,
            },
            {
              time_epoch: 1700537400,
              time: "2023-11-21 09:00",
              temp_c: 23.7,
              temp_f: 74.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 313,
              wind_dir: "NW",
              pressure_mb: 1017.0,
              pressure_in: 30.04,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 26,
              cloud: 0,
              feelslike_c: 23.6,
              feelslike_f: 74.5,
              windchill_c: 23.7,
              windchill_f: 74.7,
              heatindex_c: 23.6,
              heatindex_f: 74.5,
              dewpoint_c: 3.1,
              dewpoint_f: 37.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.3,
              gust_kph: 6.9,
              uv: 6.0,
            },
            {
              time_epoch: 1700541000,
              time: "2023-11-21 10:00",
              temp_c: 25.3,
              temp_f: 77.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 289,
              wind_dir: "WNW",
              pressure_mb: 1017.0,
              pressure_in: 30.04,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 23,
              cloud: 0,
              feelslike_c: 24.3,
              feelslike_f: 75.8,
              windchill_c: 25.3,
              windchill_f: 77.5,
              heatindex_c: 24.3,
              heatindex_f: 75.8,
              dewpoint_c: 2.9,
              dewpoint_f: 37.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.7,
              gust_kph: 9.1,
              uv: 7.0,
            },
            {
              time_epoch: 1700544600,
              time: "2023-11-21 11:00",
              temp_c: 26.6,
              temp_f: 79.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 294,
              wind_dir: "WNW",
              pressure_mb: 1016.0,
              pressure_in: 30.01,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 21,
              cloud: 0,
              feelslike_c: 25.0,
              feelslike_f: 77.1,
              windchill_c: 26.6,
              windchill_f: 79.9,
              heatindex_c: 25.0,
              heatindex_f: 77.1,
              dewpoint_c: 2.8,
              dewpoint_f: 37.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.9,
              gust_kph: 9.5,
              uv: 7.0,
            },
            {
              time_epoch: 1700548200,
              time: "2023-11-21 12:00",
              temp_c: 27.6,
              temp_f: 81.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 293,
              wind_dir: "WNW",
              pressure_mb: 1015.0,
              pressure_in: 29.97,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 20,
              cloud: 0,
              feelslike_c: 25.7,
              feelslike_f: 78.3,
              windchill_c: 27.6,
              windchill_f: 81.7,
              heatindex_c: 25.7,
              heatindex_f: 78.3,
              dewpoint_c: 2.5,
              dewpoint_f: 36.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.6,
              uv: 7.0,
            },
            {
              time_epoch: 1700551800,
              time: "2023-11-21 13:00",
              temp_c: 28.3,
              temp_f: 83.0,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 291,
              wind_dir: "WNW",
              pressure_mb: 1014.0,
              pressure_in: 29.94,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 18,
              cloud: 1,
              feelslike_c: 26.3,
              feelslike_f: 79.4,
              windchill_c: 28.4,
              windchill_f: 83.0,
              heatindex_c: 26.3,
              heatindex_f: 79.4,
              dewpoint_c: 1.8,
              dewpoint_f: 35.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 7.0,
            },
            {
              time_epoch: 1700555400,
              time: "2023-11-21 14:00",
              temp_c: 28.8,
              temp_f: 83.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13.0,
              wind_degree: 298,
              wind_dir: "WNW",
              pressure_mb: 1013.0,
              pressure_in: 29.91,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 16,
              cloud: 5,
              feelslike_c: 26.7,
              feelslike_f: 80.0,
              windchill_c: 28.8,
              windchill_f: 83.8,
              heatindex_c: 26.7,
              heatindex_f: 80.0,
              dewpoint_c: 1.0,
              dewpoint_f: 33.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.3,
              gust_kph: 14.9,
              uv: 7.0,
            },
            {
              time_epoch: 1700559000,
              time: "2023-11-21 15:00",
              temp_c: 28.8,
              temp_f: 83.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 302,
              wind_dir: "WNW",
              pressure_mb: 1012.0,
              pressure_in: 29.89,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 16,
              cloud: 13,
              feelslike_c: 26.7,
              feelslike_f: 80.1,
              windchill_c: 28.8,
              windchill_f: 83.9,
              heatindex_c: 26.7,
              heatindex_f: 80.1,
              dewpoint_c: 0.2,
              dewpoint_f: 32.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.7,
              gust_kph: 15.7,
              uv: 7.0,
            },
            {
              time_epoch: 1700562600,
              time: "2023-11-21 16:00",
              temp_c: 28.2,
              temp_f: 82.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 295,
              wind_dir: "WNW",
              pressure_mb: 1012.0,
              pressure_in: 29.89,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 16,
              cloud: 19,
              feelslike_c: 26.2,
              feelslike_f: 79.1,
              windchill_c: 28.2,
              windchill_f: 82.8,
              heatindex_c: 26.2,
              heatindex_f: 79.1,
              dewpoint_c: 0.2,
              dewpoint_f: 32.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.8,
              gust_kph: 17.4,
              uv: 7.0,
            },
            {
              time_epoch: 1700566200,
              time: "2023-11-21 17:00",
              temp_c: 27.1,
              temp_f: 80.7,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 290,
              wind_dir: "WNW",
              pressure_mb: 1012.0,
              pressure_in: 29.9,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 17,
              cloud: 62,
              feelslike_c: 25.3,
              feelslike_f: 77.5,
              windchill_c: 27.1,
              windchill_f: 80.7,
              heatindex_c: 25.3,
              heatindex_f: 77.5,
              dewpoint_c: 0.0,
              dewpoint_f: 32.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.5,
              gust_kph: 18.5,
              uv: 1.0,
            },
            {
              time_epoch: 1700569800,
              time: "2023-11-21 18:00",
              temp_c: 26.4,
              temp_f: 79.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 288,
              wind_dir: "WNW",
              pressure_mb: 1013.0,
              pressure_in: 29.91,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 18,
              cloud: 22,
              feelslike_c: 24.8,
              feelslike_f: 76.6,
              windchill_c: 26.4,
              windchill_f: 79.5,
              heatindex_c: 24.8,
              heatindex_f: 76.6,
              dewpoint_c: -0.1,
              dewpoint_f: 31.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.6,
              gust_kph: 17.0,
              uv: 1.0,
            },
            {
              time_epoch: 1700573400,
              time: "2023-11-21 19:00",
              temp_c: 25.8,
              temp_f: 78.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 289,
              wind_dir: "WNW",
              pressure_mb: 1013.0,
              pressure_in: 29.92,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 18,
              cloud: 15,
              feelslike_c: 24.3,
              feelslike_f: 75.8,
              windchill_c: 25.8,
              windchill_f: 78.4,
              heatindex_c: 24.3,
              heatindex_f: 75.8,
              dewpoint_c: -0.2,
              dewpoint_f: 31.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.8,
              gust_kph: 15.7,
              uv: 1.0,
            },
            {
              time_epoch: 1700577000,
              time: "2023-11-21 20:00",
              temp_c: 25.1,
              temp_f: 77.2,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 286,
              wind_dir: "WNW",
              pressure_mb: 1014.0,
              pressure_in: 29.94,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 19,
              cloud: 32,
              feelslike_c: 23.9,
              feelslike_f: 74.9,
              windchill_c: 25.1,
              windchill_f: 77.2,
              heatindex_c: 23.9,
              heatindex_f: 74.9,
              dewpoint_c: -0.1,
              dewpoint_f: 31.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.3,
              gust_kph: 18.2,
              uv: 1.0,
            },
            {
              time_epoch: 1700580600,
              time: "2023-11-21 21:00",
              temp_c: 24.2,
              temp_f: 75.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 294,
              wind_dir: "WNW",
              pressure_mb: 1014.0,
              pressure_in: 29.95,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 20,
              cloud: 6,
              feelslike_c: 23.3,
              feelslike_f: 73.9,
              windchill_c: 24.2,
              windchill_f: 75.5,
              heatindex_c: 23.3,
              heatindex_f: 73.9,
              dewpoint_c: -0.1,
              dewpoint_f: 31.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.1,
              gust_kph: 19.5,
              uv: 1.0,
            },
            {
              time_epoch: 1700584200,
              time: "2023-11-21 22:00",
              temp_c: 23.6,
              temp_f: 74.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 304,
              wind_dir: "NW",
              pressure_mb: 1014.0,
              pressure_in: 29.95,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 21,
              cloud: 5,
              feelslike_c: 23.0,
              feelslike_f: 73.4,
              windchill_c: 23.6,
              windchill_f: 74.4,
              heatindex_c: 23.0,
              heatindex_f: 73.4,
              dewpoint_c: -0.0,
              dewpoint_f: 31.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.2,
              gust_kph: 19.6,
              uv: 1.0,
            },
            {
              time_epoch: 1700587800,
              time: "2023-11-21 23:00",
              temp_c: 23.0,
              temp_f: 73.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1014.0,
              pressure_in: 29.94,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 22,
              cloud: 6,
              feelslike_c: 22.8,
              feelslike_f: 73.0,
              windchill_c: 23.0,
              windchill_f: 73.3,
              heatindex_c: 22.8,
              heatindex_f: 73.0,
              dewpoint_c: -0.1,
              dewpoint_f: 31.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.8,
              gust_kph: 19.0,
              uv: 1.0,
            },
          ],
        },
      ],
    },
  },
};

const store = (set, get) => ({
  ...initialState,
  useResetAll: () => set({ ...initialState }),

  fetchForCast: async (searchTerm) => {
    try {
      const data = await getForcastData(searchTerm);
      console.log(data.forecast.forecastday);
      set({ data: data });
    } catch (error) {
      console.log(error);
    }
  },
});

const useForcastStore = create(store);
export default useForcastStore;
