import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Base url  http://api.weatherapi.com/v1
//Base url with key : https://api.weatherapi.com/v1/current.json?key=ca98d66223f34543bd9190426231511&q=india
//Base Main https://api.weatherapi.com/v1/forecast.json?key=ca98d66223f34543bd9190426231511&q=india

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-8 bg-dark-body text-text-main">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
